### ISSUE TITLE
[Feature Request] add custom hover

### ISSUE THREAD

**Issue by ysv1337** [jpenilla/MiniMOTD#230] opened 2024-09-19 16:13 UTC
title

**Comment by jpenilla** [comment] 2024-09-19 18:10
I assume this is a duplicate of #70, but there is so little information provided that I don't know, which makes this issue invalid either way.

**Closed by jpenilla** 2024-09-19 18:10 UTC
Labels: enhancement

**Comment by ysv1337** [comment] 2024-09-24 00:06
why don't you add it to minimotd?
