### ISSUE TITLE
[Bug Report] Config comments duplicating

### ISSUE THREAD

**Issue by Reava** [jpenilla/MiniMOTD#190] opened 2024-05-05 13:59 UTC
**Describe the bug**
In the main config file, if the comments about the icon config is erased, the mod will automatically paste it back on every single motd entry, this can be quite annoying in very large motd collections, since it doubles the line count of every motd entry.

**To Reproduce**
1. have at least 2 motds
2. remove any comment from these lines
3. save file & reload the config
4. See issue

**Expected behavior**
Comments don't need to be parsed on each one, have them be above the first motd or not reparse after deletion.

**Server Software and Version:**
 - Vendor: Fabric
 - Minecraft Version: 1.20.4
 - minimotd-fabric-mc1.20.4-2.1.0

**Comment by jpenilla** [comment] 2024-05-05 16:37
Duplicate of #177

**Closed** 2024-05-05 16:37 UTC
Labels: bug, unconfirmed
